package config

const (
	MAX_COMMITTEES_PER_SLOT          = 4
	TARGET_COMMITTEE_SIZE            = 4
	MAX_VALIDATORS_PER_COMMITTEE     = 2048
	SHUFFLE_ROUND_COUNT              = 10
	HYSTERESIS_QUOTIENT              = 4
	HYSTERESIS_DOWNWARD_MULTIPLIER   = 1
	HYSTERESIS_UPWARD_MULTIPLIER     = 5
	SAFE_SLOTS_TO_UPDATE_JUSTIFIED   = 2
	MIN_DEPOSIT_AMOUNT               = 1_000_000_000
	MAX_EFFECTIVE_BALANCE            = 32_000_000_000
	EFFECTIVE_BALANCE_INCREMENT      = 1_000_000_000
	MIN_ATTESTATION_INCLUSION_DELAY  = 1
	SLOTS_PER_EPOCH                  = 8
	MIN_SEED_LOOKAHEAD               = 1
	MAX_SEED_LOOKAHEAD               = 4
	EPOCHS_PER_ETH1_VOTING_PERIOD    = 4
	SLOTS_PER_HISTORICAL_ROOT        = 64
	MIN_EPOCHS_TO_INACTIVITY_PENALTY = 4
	EPOCHS_PER_HISTORICAL_VECTOR     = 64
	EPOCHS_PER_SLASHINGS_VECTOR      = 64
	HISTORICAL_ROOTS_LIMIT           = 1 << 24
	VALIDATOR_REGISTRY_LIMIT         = 1 << 40
	BASE_REWARD_FACTOR               = 64
	WHISTLEBLOWER_REWARD_QUOTIENT    = 512
	PROPOSER_REWARD_QUOTIENT         = 8
	INACTIVITY_PENALTY_QUOTIENT      = 1 << 25
	MIN_SLASHING_PENALTY_QUOTIENT    = 64
	PROPORTIONAL_SLASHING_MULTIPLIER = 2
	MAX_PROPOSER_SLASHINGS           = 16
	MAX_ATTESTER_SLASHINGS           = 2
	MAX_ATTESTATIONS                 = 128
	MAX_DEPOSITS                     = 16
	MAX_VOLUNTARY_EXITS              = 16

	GENESIS_EPOCH = 0
)
